# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogoAlquilarPrenda.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlquilarPrenda(object):
    def setupUi(self, AlquilarPrenda):
        AlquilarPrenda.setObjectName("AlquilarPrenda")
        AlquilarPrenda.resize(400, 158)
        self.buttonBox = QtWidgets.QDialogButtonBox(AlquilarPrenda)
        self.buttonBox.setGeometry(QtCore.QRect(50, 120, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(AlquilarPrenda)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 381, 81))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.le_cedula = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_cedula.setObjectName("le_cedula")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_cedula)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.le_codigo = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_codigo.setObjectName("le_codigo")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_codigo)
        self.le_dias = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_dias.setObjectName("le_dias")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_dias)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)

        self.retranslateUi(AlquilarPrenda)
        self.buttonBox.accepted.connect(AlquilarPrenda.accept) # type: ignore
        self.buttonBox.rejected.connect(AlquilarPrenda.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AlquilarPrenda)

    def retranslateUi(self, AlquilarPrenda):
        _translate = QtCore.QCoreApplication.translate
        AlquilarPrenda.setWindowTitle(_translate("AlquilarPrenda", "Dialog"))
        self.label_4.setText(_translate("AlquilarPrenda", "Cédula:"))
        self.label_5.setText(_translate("AlquilarPrenda", "Código:"))
        self.label_6.setText(_translate("AlquilarPrenda", "Días:"))
