# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogoRegistrarUsuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgregarUsuario(object):
    def setupUi(self, AgregarUsuario):
        AgregarUsuario.setObjectName("AgregarUsuario")
        AgregarUsuario.resize(400, 162)
        self.buttonBox = QtWidgets.QDialogButtonBox(AgregarUsuario)
        self.buttonBox.setGeometry(QtCore.QRect(230, 120, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(AgregarUsuario)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 381, 80))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.le_nombre = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_nombre.setObjectName("le_nombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_nombre)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_cedula = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_cedula.setObjectName("le_cedula")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_cedula)
        self.le_correo = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_correo.setObjectName("le_correo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_correo)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)

        self.retranslateUi(AgregarUsuario)
        self.buttonBox.accepted.connect(AgregarUsuario.accept) # type: ignore
        self.buttonBox.rejected.connect(AgregarUsuario.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AgregarUsuario)

    def retranslateUi(self, AgregarUsuario):
        _translate = QtCore.QCoreApplication.translate
        AgregarUsuario.setWindowTitle(_translate("AgregarUsuario", "Dialog"))
        self.label.setText(_translate("AgregarUsuario", "Nombre:"))
        self.label_2.setText(_translate("AgregarUsuario", "Cédula:"))
        self.label_3.setText(_translate("AgregarUsuario", "Correo:"))
