# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogoComprarPrenda.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ComprarPrenda(object):
    def setupUi(self, ComprarPrenda):
        ComprarPrenda.setObjectName("ComprarPrenda")
        ComprarPrenda.resize(400, 131)
        self.buttonBox = QtWidgets.QDialogButtonBox(ComprarPrenda)
        self.buttonBox.setGeometry(QtCore.QRect(50, 90, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(ComprarPrenda)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 381, 51))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.le_cedula = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_cedula.setObjectName("le_cedula")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_cedula)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.le_codigo = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_codigo.setObjectName("le_codigo")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_codigo)

        self.retranslateUi(ComprarPrenda)
        self.buttonBox.accepted.connect(ComprarPrenda.accept) # type: ignore
        self.buttonBox.rejected.connect(ComprarPrenda.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ComprarPrenda)

    def retranslateUi(self, ComprarPrenda):
        _translate = QtCore.QCoreApplication.translate
        ComprarPrenda.setWindowTitle(_translate("ComprarPrenda", "Dialog"))
        self.label_4.setText(_translate("ComprarPrenda", "Cédula:"))
        self.label_5.setText(_translate("ComprarPrenda", "Código:"))
